name: package
on:
  push:
    tags:   # run workflow on pushing a tag, atm relies on user inputting valid semver, could make it do checks with regex if required.
      - '*'


env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  PushedTag: ${{ github.ref_name}} # save the pushed tag for later use after deleting them
  NuGetDirectory: ${{ github.workspace}}/nuget

defaults:
  run:
    shell: bash # changed to bash to get it working, could change to powershell again but might need to fix syntax

jobs:
  create_nuget:
    runs-on: ubuntu-latest
    steps:
    - name: checkout and delete existing tags on github, then create local tag for use by gitversion
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Get all history to allow automatic versioning using GitVersion
    
    #find highest existing tag and check if it's higher than or equal to pushed tag. 
    #if not highest tag remove new tag and exit with status 1. one issue is it might rebuild if it's same tag is pushed twice but github should stop that
    - name: abort if pushed tag is lower than highest existing tag
      run: |
        if [[ $(git tag | sort -r --version-sort | head -n1) != ${{env.PushedTag}} ]]; then \
          echo pushed tag is lower than existing tags, aborting... && \
          git push -d origin ${{env.PushedTag}} && \
          exit 1; \
        else \
          echo continue with package build; \
        fi

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # deletes all tags within virtual machine then remakes pushed tag for use by gitversion
    # unnecessary with new behaviour, this is if we want to build with lower tags than highest existing
    - name: reset tags
      run: |
       git tag -l | xargs git tag -d
       git tag ${{env.PushedTag}}

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3.1.11
      with:
        versionSpec: '6.0.0'
    

    - name: Use GitVersion
      id: gitVersion
      uses: gittools/actions/gitversion/execute@v3.1.11

    # Run dotnet tests and output dll in default location
    - run: dotnet test --configuration Release
    # Create the NuGet package in the folder from the environment variable NuGetDirectory, 
    # using the dll output from the test step above
    - run: |
        dotnet pack \
        --configuration Release \
        -p:PackageVersion=${{steps.gitVersion.outputs.FullSemVer}} \
        --output ${{ env.NuGetDirectory }}

    # Publish the NuGet package as an artifact, so they can be used in the following jobs
    - uses: actions/upload-artifact@v4
      with:
        name: nuget
        if-no-files-found: error
        retention-days: 1 # lowered retention cause i'm making a bunch of these while testing stuff
        path: ${{ env.NuGetDirectory }}/*.nupkg

